# Generated by Django 5.1.5 on 2025-05-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('adrar', 'Adrar'), ('chlef', 'Chlef'), ('laghouat', 'Laghouat'), ('oum-el-bouaghi', 'Oum El Bouaghi'), ('batna', 'Batna'), ('bejaia', 'Béjaïa'), ('biskra', 'Biskra'), ('bechar', 'Béchar'), ('blida', 'Blida'), ('bouira', 'Bouira'), ('tamanrasset', 'Tamanrasset'), ('tebessa', 'Tébessa'), ('tlemcen', 'Tlemcen'), ('tiaret', 'Tiaret'), ('tizi-ouzou', 'Tizi Ouzou'), ('algiers', 'Algiers'), ('djelfa', 'Djelfa'), ('jijel', 'Jijel'), ('setif', 'Sétif'), ('saida', 'Saïda'), ('skikda', 'Skikda'), ('sidi-bel-abbes', 'Sidi Bel Abbès'), ('annaba', 'Annaba'), ('guelma', 'Guelma'), ('constantine', 'Constantine'), ('medea', 'Médéa'), ('mostaganem', 'Mostaganem'), ('msila', "M'Sila"), ('mascara', 'Mascara'), ('ouargla', 'Ouargla'), ('oran', 'Oran'), ('el-bayadh', 'El Bayadh'), ('illizi', 'Illizi'), ('bordj-bou-arreridj', 'Bordj Bou Arréridj'), ('boumerdes', 'Boumerdès'), ('el-tarf', 'El Tarf'), ('tindouf', 'Tindouf'), ('tissemsilt', 'Tissemsilt'), ('el-oued', 'El Oued'), ('khenchela', 'Khenchela'), ('souk-ahras', 'Souk Ahras'), ('tipaza', 'Tipaza'), ('mila', 'Mila'), ('ain-defla', 'Aïn Defla'), ('naama', 'Naâma'), ('ain-temouchent', 'Aïn Témouchent'), ('ghardaia', 'Ghardaïa'), ('relizane', 'Relizane'), ('timimoun', 'Timimoun'), ('bordj-badji-mokhtar', 'Bordj Badji Mokhtar'), ('ouled-djellal', 'Ouled Djellal'), ('beni-abbes', 'Béni Abbès'), ('in-salah', 'In Salah'), ('in-guezzam', 'In Guezzam'), ('touggourt', 'Touggourt'), ('djanet', 'Djanet'), ('el-mghair', "El M'Ghair"), ('el-menia', 'El Menia')], max_length=100, verbose_name='region'),
        ),
    ]
