# Generated by Django 5.1.5 on 2025-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_agency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='delivery agency'),
        ),
    ]
