# Generated by Django 5.2.7 on 2025-10-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delivery_agency'),
    ]

    operations = [
        # Drop blog tables
        migrations.RunSQL(
            "DROP TABLE IF EXISTS blog_blogpost_likes;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS blog_blogpost;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
