services:
  - type: web
    name: crafty-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: gunicorn crafty.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: crafty-django.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: crafty-db
          property: connectionString

databases:
  - name: crafty-db
    databaseName: crafty
    user: crafty_user
