# Generated by Django 5.2.7 on 2025-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_notification_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Someone liked your post'), ('comment', 'Someone commented on your post'), ('connection_request', 'New connection request'), ('connection_accepted', 'Connection request accepted'), ('connection_rejected', 'Connection request declined'), ('message', 'New message'), ('mention', 'You were mentioned')], max_length=20, verbose_name='notification type'),
        ),
    ]
