# Generated by Django 5.2.7 on 2025-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this post is visible to non-authenticated users', verbose_name='public'),
        ),
    ]
