# Generated by Django 5.2.7 on 2025-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('work', 'Work Showcase'), ('tip', 'Tip & Tutorial'), ('story', 'Story'), ('question', 'Question'), ('completed', 'Completed Work'), ('wip', 'Work in Progress'), ('inspiration', 'Inspiration'), ('tutorial', 'Tutorial'), ('announcement', 'Announcement')], default='completed', max_length=20, verbose_name='post type'),
        ),
    ]
