# Generated by Django 5.2.7 on 2025-11-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community/posts/videos', verbose_name='video'),
        ),
    ]
