# Generated by Django 5.2.7 on 2025-11-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, help_text='Post shared in this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_messages', to='community.post'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
    ]
