# Generated by Django 5.1.5 on 2025-05-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='artist name')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('availability', models.BooleanField(default=True, verbose_name='available for commissions')),
                ('featured', models.BooleanField(default=False, verbose_name='featured artist')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'ordering': ['-created_at'],
            },
        ),
    ]
