# Generated by Django 5.1.5 on 2025-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='craft_category',
            field=models.CharField(blank=True, choices=[('Pottery', 'Pottery'), ('Embroidery', 'Embroidery'), ('Woodworking', 'Woodworking'), ('Leatherwork', 'Leatherwork'), ('Weaving', 'Weaving'), ('Jewelry Making', 'Jewelry Making'), ('Calligraphy', 'Calligraphy'), ('Glass Art', 'Glass Art'), ('Painting', 'Painting'), ('Crochet/Knitting', 'Crochet/Knitting')], max_length=20, verbose_name='craft category'),
        ),
    ]
