# Generated by Django 5.1.5 on 2025-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='craft_category',
            field=models.CharField(blank=True, choices=[('pottery', 'Pottery'), ('embroidery', 'Embroidery'), ('woodworking', 'Woodworking'), ('leatherwork', 'Leatherwork'), ('weaving', 'Weaving'), ('jewelry', 'Jewelry Making'), ('calligraphy', 'Calligraphy'), ('glass-art', 'Glass Art'), ('painting', 'Painting'), ('crochet-knitting', 'Crochet/Knitting')], max_length=20, verbose_name='craft category'),
        ),
    ]
