# Generated by Django 5.1.5 on 2025-05-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_craft_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='craft_category',
            field=models.CharField(blank=True, choices=[('traditional', 'Traditional'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('jewelry', 'Jewelry'), ('home-decor', 'Home Decor'), ('crockery', 'Crockery'), ('toys-games', 'Toys & Games'), ('art-painting', 'Art & Painting'), ('gift-ideas', 'Gift Ideas')], max_length=20, verbose_name='craft category'),
        ),
    ]
